### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by aditdoshi333** [engcang/FAST-LIO-Localization-QN#1]
Hello,

Thanks for sharing the work. Any plan to release the complete code?

**Comment by engcang** [comment]
Hi @aditdoshi333 
Thank you for your interest in my work!
the code already works with Quatro disabled!
With Quatro enabled, since too many pairs of correspondences are matched, computation for map matching is super slow now. Hence, downsampling the correspondences is on the to do list of us and it will be completed in the near future.
Let me tell you when it is done :)

**Comment by engcang** [comment]
@aditdoshi333 Hi.
Thank you for your patience and I can happily tell you that the code is now completed with Quatro enabled in real time utilizing `optimizedMatching` method, which includes many optimized parallel computation and downsampling.
